--
-- PostgreSQL database dump
--


-- Dumped from database version 16.13 (Ubuntu 16.13-1.pgdg24.04+1)
-- Dumped by pg_dump version 16.13 (Ubuntu 16.13-1.pgdg24.04+1)

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

ALTER TABLE IF EXISTS ONLY public.postcodes DROP CONSTRAINT IF EXISTS postcodes_state_id_fkey;
ALTER TABLE IF EXISTS ONLY public.postcodes DROP CONSTRAINT IF EXISTS postcodes_country_id_fkey;
ALTER TABLE IF EXISTS ONLY public.postcodes DROP CONSTRAINT IF EXISTS postcodes_city_id_fkey;
DROP INDEX IF EXISTS public.postcodes_state_id_idx;
DROP INDEX IF EXISTS public.postcodes_country_id_code_idx;
DROP INDEX IF EXISTS public.postcodes_code_idx;
DROP INDEX IF EXISTS public.postcodes_city_id_idx;
ALTER TABLE IF EXISTS ONLY public.postcodes DROP CONSTRAINT IF EXISTS postcodes_pkey;
DROP TABLE IF EXISTS public.postcodes;
SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: postcodes; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.postcodes (
    id bigint NOT NULL,
    code character varying(20) NOT NULL,
    country_id bigint NOT NULL,
    country_code character(2) NOT NULL,
    state_id bigint,
    state_code character varying(255),
    city_id bigint,
    locality_name character varying(255),
    type character varying(32),
    latitude numeric(10,8),
    longitude numeric(11,8),
    source character varying(64),
    "wikiDataId" character varying(255),
    created_at timestamp without time zone DEFAULT '2014-01-01 12:01:01'::timestamp without time zone NOT NULL,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP NOT NULL,
    flag smallint DEFAULT 1 NOT NULL
);


--
-- Name: TABLE postcodes; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON TABLE public.postcodes IS 'Postal codes (issue #1039) - Tier 4: one row per postcode';


--
-- Name: COLUMN postcodes.code; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes.code IS 'The postal code value (alphanumeric, country-specific format)';


--
-- Name: COLUMN postcodes.locality_name; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes.locality_name IS 'Human-readable place name associated with the postcode';


--
-- Name: COLUMN postcodes.type; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes.type IS 'Granularity: full | outward | sector | district | area';


--
-- Name: COLUMN postcodes.source; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes.source IS 'Originating data source for license/attribution tracking (e.g. openplz, wikidata, census)';


--
-- Name: COLUMN postcodes."wikiDataId"; Type: COMMENT; Schema: public; Owner: -
--

COMMENT ON COLUMN public.postcodes."wikiDataId" IS 'Wikidata Q-ID for cross-referencing';


--
-- Name: postcodes_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.postcodes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.postcodes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Data for Name: postcodes; Type: TABLE DATA; Schema: public; Owner: -
--

INSERT INTO public.postcodes VALUES (1, 'AD100', 6, 'AD', 489, '02', NULL, 'Canillo', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (2, 'AD200', 6, 'AD', 487, '03', NULL, 'Encamp', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (3, 'AD300', 6, 'AD', 491, '05', NULL, 'Ordino', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (4, 'AD400', 6, 'AD', 493, '04', NULL, 'La Massana', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (5, 'AD500', 6, 'AD', 488, '07', NULL, 'Andorra la Vella', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (6, 'AD600', 6, 'AD', 490, '06', NULL, 'Sant Julia de Loria', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (7, 'AD700', 6, 'AD', 492, '08', NULL, 'Escaldes-Engordany', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (8, '96799', 5, 'AS', NULL, NULL, NULL, 'American Samoa', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (9, '97133', 189, 'BL', NULL, NULL, NULL, 'Saint-Barthelemy', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (10, '96941', 143, 'FM', 2581, 'PNI', NULL, 'Pohnpei', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (11, '96942', 143, 'FM', 2580, 'TRK', NULL, 'Chuuk', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (12, '96943', 143, 'FM', 2582, 'YAP', NULL, 'Yap', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (13, '96944', 143, 'FM', 2583, 'KSA', NULL, 'Kosrae', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (14, '97300', 76, 'GF', NULL, NULL, NULL, 'Cayenne', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (15, '97310', 76, 'GF', NULL, NULL, NULL, 'Kourou', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (16, '97320', 76, 'GF', NULL, NULL, NULL, 'Saint-Laurent-du-Maroni', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (17, 'GX11 1AA', 84, 'GI', NULL, NULL, NULL, 'Gibraltar', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (18, '3900', 86, 'GL', 5383, 'SM', NULL, 'Nuuk', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (19, '3911', 86, 'GL', 5382, 'QE', NULL, 'Sisimiut', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (20, '3912', 86, 'GL', 5382, 'QE', NULL, 'Maniitsoq', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (21, '3920', 86, 'GL', 5380, 'KU', NULL, 'Qaqortoq', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (22, '3922', 86, 'GL', 5380, 'KU', NULL, 'Nanortalik', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (23, '3940', 86, 'GL', 5383, 'SM', NULL, 'Paamiut', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (24, '3950', 86, 'GL', 5381, 'QT', NULL, 'Aasiaat', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (25, '3952', 86, 'GL', 5379, 'AV', NULL, 'Ilulissat', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (26, '3971', 86, 'GL', 5379, 'AV', NULL, 'Qaanaaq', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (27, '3980', 86, 'GL', 5383, 'SM', NULL, 'Ittoqqortoormiit', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (28, '9485', 125, 'LI', 451, '02', NULL, 'Nendeln', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (29, '9486', 125, 'LI', 455, '04', NULL, 'Schaanwald', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (30, '9487', 125, 'LI', 457, '03', NULL, 'Bendern', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (31, '9488', 125, 'LI', 449, '08', NULL, 'Schellenberg', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (32, '9490', 125, 'LI', 452, '11', NULL, 'Vaduz', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (33, '9491', 125, 'LI', 453, '06', NULL, 'Ruggell', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (34, '9492', 125, 'LI', 451, '02', NULL, 'Eschen', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (35, '9493', 125, 'LI', 455, '04', NULL, 'Mauren', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (36, '9494', 125, 'LI', 450, '07', NULL, 'Schaan', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (37, '9495', 125, 'LI', 459, '09', NULL, 'Triesen', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (38, '9496', 125, 'LI', 458, '01', NULL, 'Balzers', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (39, '9497', 125, 'LI', 456, '10', NULL, 'Triesenberg', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (40, '9498', 125, 'LI', 454, '05', NULL, 'Planken', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (41, '98000', 145, 'MC', NULL, NULL, NULL, 'Monaco', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (42, '97150', 190, 'MF', NULL, NULL, NULL, 'Saint-Martin', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (43, '96960', 137, 'MH', 5656, 'MAJ', NULL, 'Majuro', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (44, '96970', 137, 'MH', 5652, 'KWA', NULL, 'Ebeye', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (45, '96950', 164, 'MP', NULL, NULL, NULL, 'Saipan', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (46, '96951', 164, 'MP', NULL, NULL, NULL, 'Rota', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (47, '96952', 164, 'MP', NULL, NULL, NULL, 'Tinian', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (48, '98800', 157, 'NC', 5225, '01', NULL, 'Noumea', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (49, '98860', 157, 'NC', 5226, '02', NULL, 'Kone', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (50, '98820', 157, 'NC', 5227, '03', NULL, 'We', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (51, '96940', 168, 'PW', NULL, NULL, NULL, 'Palau', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (52, '47890', 192, 'SM', 58, '07', NULL, 'San Marino', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (53, '47891', 192, 'SM', 65, '09', NULL, 'Serravalle', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (54, '47892', 192, 'SM', 59, '01', NULL, 'Acquaviva', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (55, '47893', 192, 'SM', 61, '06', NULL, 'Borgo Maggiore', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (56, '47894', 192, 'SM', 60, '02', NULL, 'Chiesanuova', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (57, '47895', 192, 'SM', 64, '03', NULL, 'Domagnano', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (58, '47896', 192, 'SM', 62, '04', NULL, 'Faetano', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (59, '47897', 192, 'SM', 66, '05', NULL, 'Fiorentino', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (60, '47898', 192, 'SM', 63, '08', NULL, 'Montegiardino', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (61, '00120', 238, 'VA', NULL, NULL, NULL, 'Citta del Vaticano', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (62, '98600', 243, 'WF', 5707, 'UV', NULL, 'Mata-Utu', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);
INSERT INTO public.postcodes VALUES (63, '97600', 141, 'YT', 5404, '03', NULL, 'Mamoudzou', 'full', NULL, NULL, 'manual', NULL, '2026-04-25 17:16:28', '2026-04-25 17:16:28', 1);


--
-- Name: postcodes_id_seq; Type: SEQUENCE SET; Schema: public; Owner: -
--

SELECT pg_catalog.setval('public.postcodes_id_seq', 63, true);


--
-- Name: postcodes postcodes_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcodes
    ADD CONSTRAINT postcodes_pkey PRIMARY KEY (id);


--
-- Name: postcodes_city_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcodes_city_id_idx ON public.postcodes USING btree (city_id);


--
-- Name: postcodes_code_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcodes_code_idx ON public.postcodes USING btree (code);


--
-- Name: postcodes_country_id_code_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcodes_country_id_code_idx ON public.postcodes USING btree (country_id, code);


--
-- Name: postcodes_state_id_idx; Type: INDEX; Schema: public; Owner: -
--

CREATE INDEX postcodes_state_id_idx ON public.postcodes USING btree (state_id);


--
-- Name: postcodes postcodes_city_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcodes
    ADD CONSTRAINT postcodes_city_id_fkey FOREIGN KEY (city_id) REFERENCES public.cities(id) ON DELETE SET NULL;


--
-- Name: postcodes postcodes_country_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcodes
    ADD CONSTRAINT postcodes_country_id_fkey FOREIGN KEY (country_id) REFERENCES public.countries(id);


--
-- Name: postcodes postcodes_state_id_fkey; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.postcodes
    ADD CONSTRAINT postcodes_state_id_fkey FOREIGN KEY (state_id) REFERENCES public.states(id) ON DELETE SET NULL;


--
-- PostgreSQL database dump complete
--


